<?xml version="1.0" encoding="utf-8"?>
<testsuites time="34.192" tests="52" failures="52">
  <testsuite id="0" name="Source.TestSubmission.dll" tests="52" failures="52" time="34.192">
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Table" time="8.4370000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CompanyModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Field(fieldName: &quot;created_at&quot;, isNullable: False, fieldType: typeof(System.DateTime), fieldSize: null)" time="0.0160000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Field(fieldName: &quot;id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0090000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Field(fieldName: &quot;challenge_id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0020000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CompanyModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at System.Lazy`1.CreateValue()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 35
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Field(fieldName: &quot;name&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 100)" time="0.0040000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.CompanyModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Field(fieldName: &quot;slug&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 50)" time="0.0050000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.CompanyModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 25</error>
    </testcase>
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Primary_Key" time="0.0110000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---</error>
    </testcase>
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Children_Navigation(childrenTable: &quot;candidate&quot;)" time="0.0060000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 19</error>
    </testcase>
    <testcase classname="Codenation.Challenge.AccelerationModelTest" name="Codenation.Challenge.AccelerationModelTest.Should_Has_Foreing_Key(fieldName: &quot;challenge_id&quot;, relatedTable: &quot;challenge&quot;, isNullable: False, relatedKey: &quot;id&quot;)" time="0.0070000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 43</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(fieldName: &quot;company_id&quot;, relatedTable: &quot;company&quot;, isNullable: False, relatedKey: &quot;id&quot;)" time="0.0080000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 45</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(fieldName: &quot;user_id&quot;, relatedTable: &quot;user&quot;, isNullable: False, relatedKey: &quot;id&quot;)" time="0.0340000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.UserModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 37</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(fieldName: &quot;acceleration_id&quot;, relatedTable: &quot;acceleration&quot;, isNullable: False, relatedKey: &quot;id&quot;)" time="0.0050000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 45</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Table" time="0.0050000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.UserModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.CandidateModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 19</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Field(fieldName: &quot;company_id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0060000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CandidateModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Field(fieldName: &quot;user_id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0030000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CandidateModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Field(fieldName: &quot;acceleration_id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0050000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.UserModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 37</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Field(fieldName: &quot;created_at&quot;, isNullable: False, fieldType: typeof(System.DateTime), fieldSize: null)" time="0.0050000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CandidateModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Field(fieldName: &quot;status&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0040000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CandidateModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.UserModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 19</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CandidateModelTest" name="Codenation.Challenge.CandidateModelTest.Should_Has_Primary_Key" time="0.0080000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.CandidateModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 25</error>
    </testcase>
    <testcase classname="Codenation.Challenge.ChallengeModelTest" name="Codenation.Challenge.ChallengeModelTest.Should_Has_Field(fieldName: &quot;name&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 100)" time="8.4380000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CompanyModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.ChallengeModelTest" name="Codenation.Challenge.ChallengeModelTest.Should_Has_Field(fieldName: &quot;slug&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 50)" time="0.0100000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.ChallengeModelTest" name="Codenation.Challenge.ChallengeModelTest.Should_Has_Field(fieldName: &quot;id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0100000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.ChallengeModelTest" name="Codenation.Challenge.ChallengeModelTest.Should_Has_Field(fieldName: &quot;created_at&quot;, isNullable: False, fieldType: typeof(System.DateTime), fieldSize: null)" time="0.0030000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CompanyModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at System.Lazy`1.CreateValue()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 35
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.ChallengeModelTest" name="Codenation.Challenge.ChallengeModelTest.Should_Has_Children_Navigation(childrenTable: &quot;acceleration&quot;)" time="0.0110000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertChildrenNavigation(String navigationTable) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 133
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Children_Navigation(String childrenTable) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 43</error>
    </testcase>
    <testcase classname="Codenation.Challenge.ChallengeModelTest" name="Codenation.Challenge.ChallengeModelTest.Should_Has_Children_Navigation(childrenTable: &quot;submission&quot;)" time="0.0040000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.CompanyModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 25</error>
    </testcase>
    <testcase classname="Codenation.Challenge.ChallengeModelTest" name="Codenation.Challenge.ChallengeModelTest.Should_Has_Primary_Key" time="0.0080000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---</error>
    </testcase>
    <testcase classname="Codenation.Challenge.ChallengeModelTest" name="Codenation.Challenge.ChallengeModelTest.Should_Has_Table" time="0.0050000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 19</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CompanyModelTest" name="Codenation.Challenge.CompanyModelTest.Should_Has_Field(fieldName: &quot;id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="8.4400000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CompanyModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CompanyModelTest" name="Codenation.Challenge.CompanyModelTest.Should_Has_Field(fieldName: &quot;slug&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 50)" time="0.0100000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CompanyModelTest" name="Codenation.Challenge.CompanyModelTest.Should_Has_Field(fieldName: &quot;created_at&quot;, isNullable: False, fieldType: typeof(System.DateTime), fieldSize: null)" time="0.0110000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CompanyModelTest" name="Codenation.Challenge.CompanyModelTest.Should_Has_Field(fieldName: &quot;name&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 100)" time="0.0010000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CompanyModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at System.Lazy`1.CreateValue()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 35
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CompanyModelTest" name="Codenation.Challenge.CompanyModelTest.Should_Has_Table" time="0.0080000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.CompanyModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CompanyModelTest" name="Codenation.Challenge.CompanyModelTest.Should_Has_Primary_Key" time="0.0060000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.CompanyModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 25</error>
    </testcase>
    <testcase classname="Codenation.Challenge.CompanyModelTest" name="Codenation.Challenge.CompanyModelTest.Should_Has_Children_Navigation(childrenTable: &quot;candidate&quot;)" time="0.0060000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 25</error>
    </testcase>
    <testcase classname="Codenation.Challenge.SubmissionModelTest" name="Codenation.Challenge.SubmissionModelTest.Should_Has_Primary_Key" time="8.4400000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CompanyModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.SubmissionModelTest" name="Codenation.Challenge.SubmissionModelTest.Should_Has_Field(fieldName: &quot;user_id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0100000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 35</error>
    </testcase>
    <testcase classname="Codenation.Challenge.SubmissionModelTest" name="Codenation.Challenge.SubmissionModelTest.Should_Has_Field(fieldName: &quot;created_at&quot;, isNullable: False, fieldType: typeof(System.DateTime), fieldSize: null)" time="0.0120000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.SubmissionModelTest" name="Codenation.Challenge.SubmissionModelTest.Should_Has_Field(fieldName: &quot;challenge_id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0030000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CompanyModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CompanyModelTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at System.Lazy`1.CreateValue()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 35
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 35
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.SubmissionModelTest" name="Codenation.Challenge.SubmissionModelTest.Should_Has_Field(fieldName: &quot;score&quot;, isNullable: False, fieldType: typeof(decimal), fieldSize: null)" time="0.0080000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertChildrenNavigation(String navigationTable) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 133
   at Codenation.Challenge.ChallengeModelTest.Should_Has_Children_Navigation(String childrenTable) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ChallengeModelTest.cs:line 43</error>
    </testcase>
    <testcase classname="Codenation.Challenge.SubmissionModelTest" name="Codenation.Challenge.SubmissionModelTest.Should_Has_Foreing_Key(fieldName: &quot;challenge_id&quot;, relatedTable: &quot;challenge&quot;, isNullable: False, relatedKey: &quot;id&quot;)" time="0.0380000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.AccelerationModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\AccelerationModelTest.cs:line 43</error>
    </testcase>
    <testcase classname="Codenation.Challenge.SubmissionModelTest" name="Codenation.Challenge.SubmissionModelTest.Should_Has_Foreing_Key(fieldName: &quot;user_id&quot;, relatedTable: &quot;user&quot;, isNullable: False, relatedKey: &quot;id&quot;)" time="0.0140000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 43</error>
    </testcase>
    <testcase classname="Codenation.Challenge.SubmissionModelTest" name="Codenation.Challenge.SubmissionModelTest.Should_Has_Table" time="0.0210000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.SubmissionModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\SubmissionModelTest.cs:line 19</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Field(fieldName: &quot;nickname&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 50)" time="0.0070000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 45</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Field(fieldName: &quot;password&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 255)" time="0.0320000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.UserModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 37</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Field(fieldName: &quot;full_name&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 100)" time="0.0060000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertForeignKey(String fieldName, String expectedRelatedTable, Boolean required, String[] expectedKeys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 112
   at Codenation.Challenge.CandidateModelTest.Should_Has_Foreing_Key(String fieldName, String relatedTable, Boolean isNullable, String relatedKey) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 45</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Field(fieldName: &quot;created_at&quot;, isNullable: False, fieldType: typeof(System.DateTime), fieldSize: null)" time="0.0130000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CandidateModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Field(fieldName: &quot;id&quot;, isNullable: False, fieldType: typeof(int), fieldSize: null)" time="0.0070000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CandidateModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 36</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Field(fieldName: &quot;email&quot;, isNullable: False, fieldType: typeof(string), fieldSize: 100)" time="0.0070000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.UserModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 37</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Table" time="0.0080000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertField(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 92
   at Codenation.Challenge.CandidateModelTest.Should_Has_Field(String fieldName, Boolean isNullable, Type fieldType, Nullable`1 fieldSize) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertTable() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 74
   at Codenation.Challenge.UserModelTest.Should_Has_Table() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 19</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Primary_Key" time="0.0060000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertPrimaryKeys(String[] keys) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 82
   at Codenation.Challenge.CandidateModelTest.Should_Has_Primary_Key() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\CandidateModelTest.cs:line 25</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Children_Navigation(childrenTable: &quot;candidate&quot;)" time="0.0060000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertChildrenNavigation(String navigationTable) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 133
   at Codenation.Challenge.UserModelTest.Should_Has_Children_Navigation(String childrenTable) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 45</error>
    </testcase>
    <testcase classname="Codenation.Challenge.UserModelTest" name="Codenation.Challenge.UserModelTest.Should_Has_Children_Navigation(childrenTable: &quot;submission&quot;)" time="0.0030000">
      <error message="System.InvalidOperationException : The relationship from 'Submission.User' to 'User.Submissions' with foreign key properties {'UserId' : string} cannot target the primary key {'UserId' : int} because it is not compatible. Configure a principal key or a set of compatible foreign key properties for this relationship.">   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateNoShadowKeys(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ValidatingConvention.Apply(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnModelBuilt(InternalModelBuilder modelBuilder)
   at Microsoft.EntityFrameworkCore.ModelBuilder.FinalizeModel()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at lambda_method(Closure , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Codenation.Challenge.ModelBaseTest.GetEntity() in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 26
   at Codenation.Challenge.ModelBaseTest.AssertChildrenNavigation(String navigationTable) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\ModelBaseTest.cs:line 133
   at Codenation.Challenge.UserModelTest.Should_Has_Children_Navigation(String childrenTable) in C:\Users\Danielly\codenation\csharp-7\Source.TestSubmission\UserModelTest.cs:line 45</error>
    </testcase>
  </testsuite>
</testsuites>